import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

const Terms = () => (
  <div className="min-h-screen bg-background">
    <div className="container mx-auto max-w-4xl px-6 py-16">
      <Link
        to="/"
        className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to Home
      </Link>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="prose prose-slate dark:prose-invert max-w-none"
      >
        <h1 className="font-heading text-4xl font-bold text-foreground mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Agreement to Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By installing and using Brevity, you agree to these Terms of Service. If you do not agree, 
            please do not use the extension.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            Brevity is a free, open-source browser extension that provides AI-powered email analysis features including:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-2">
            <li>Email summarization</li>
            <li>Phishing and risk detection</li>
            <li>Action item extraction</li>
            <li>AI-powered reply generation</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">User Responsibilities</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">You are responsible for:</p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>Providing and managing your own AI API key (OpenAI, Google, etc.)</li>
            <li>Any costs associated with API usage from your chosen provider</li>
            <li>Reviewing AI-generated content before acting on it</li>
            <li>Complying with your email provider's terms of service</li>
            <li>Ensuring your use complies with applicable laws and regulations</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">No Warranty</h2>
          <p className="text-muted-foreground leading-relaxed">
            Brevity is provided "as is" without warranty of any kind, express or implied. We do not guarantee that:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-2">
            <li>The extension will be error-free or uninterrupted</li>
            <li>AI-generated summaries, risk assessments, or replies will be accurate</li>
            <li>The extension will detect all phishing attempts or malicious content</li>
            <li>The extension will be compatible with future Gmail or browser updates</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            To the maximum extent permitted by law, Brevity and its developers shall not be liable for any indirect, 
            incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred 
            directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-2">
            <li>Your use or inability to use the extension</li>
            <li>Any inaccurate AI-generated content</li>
            <li>Undetected phishing or malicious emails</li>
            <li>API costs incurred from your chosen provider</li>
            <li>Any security breach or data loss</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">AI Content Disclaimer</h2>
          <p className="text-muted-foreground leading-relaxed">
            All summaries, risk assessments, and reply drafts are generated by AI and may contain errors, 
            inaccuracies, or inappropriate content. You should always review AI-generated content before acting on it. 
            Brevity is not responsible for decisions made based on AI-generated content.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Third-Party Services</h2>
          <p className="text-muted-foreground leading-relaxed">
            Brevity integrates with third-party AI services (OpenAI, Google AI, etc.). Your use of these services 
            is subject to their respective terms of service and privacy policies. Brevity is not responsible for 
            the actions, policies, or practices of third-party services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            Brevity is open-source software released under the MIT License. You are free to use, modify, and 
            distribute the code in accordance with the license terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Termination</h2>
          <p className="text-muted-foreground leading-relaxed">
            You may stop using Brevity at any time by uninstalling the extension from your browser. 
            We reserve the right to discontinue the service at any time without notice.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Changes to Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update these Terms of Service from time to time. Continued use of Brevity after changes 
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Governing Law</h2>
          <p className="text-muted-foreground leading-relaxed">
            These terms shall be governed by and construed in accordance with the laws of your jurisdiction, 
            without regard to its conflict of law provisions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-heading text-2xl font-semibold text-foreground mt-8 mb-4">Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            If you have questions about these Terms of Service, please contact us at:{" "}
            <a href="mailto:legal@brevity.email" className="text-primary hover:underline">
              legal@brevity.email
            </a>
          </p>
        </section>
      </motion.div>
    </div>
  </div>
);

export default Terms;
